// Barrel file para exportar componentes de Material-UI
// Esto evita problemas con importaciones de @mui/icons-material

// Re-exportamos los componentes que necesitamos
export {
  Box,
  Grid,
  Paper,
  Typography,
  Card,
  CardContent,
  Alert,
  Chip,
  CircularProgress,
  Container,
  Drawer,
  AppBar,
  Toolbar,
  IconButton,
  Avatar,
  useTheme,
  useMediaQuery,
  List,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Divider,
  Badge,
  Tabs,
  Tab,
  AlertTitle,
  Button,
  ButtonGroup,
  FormControl,
  Select,
  MenuItem,
  ListItemSecondaryAction,
  Stack,
  Checkbox,
  InputLabel,
  TextField,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Menu,
  Skeleton,
  Tooltip,
  Switch,
  FormControlLabel,
  LinearProgress,
  Collapse
} from '@mui/material';

// Re-exportamos utilidades del sistema
export { alpha } from '@mui/system';